<a href="https://colab.research.google.com/github/ashutoshd1996/DeepLearning-Zero-to-GANs/blob/main/Pytorch_Basics/Assignment_01_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.set_project('01-tensor-operations')
jovian.set_colab_id('1cgQCb1LQji9diJEzMcl0WyOJSqtq3FE_')

# Tensor Operations 

The torch package contains data structures for multi-dimensional tensors and defines mathematical operations over these tensors. Additionally, it provides many utilities for efficient serializing of Tensors and arbitrary types, and other useful utilities.

- torch.zeros
- torch.arange
- torch.linspace
- torch.narrow
- torch.transpose

Before we begin, let's install and import PyTorch

In [ ]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [ ]:
# Import torch and other required modules
import torch

## Function 1 - torch.zeros 

Returns a tensor filled with the scalar value 0, with the shape defined by the variable argument size.

In [ ]:
# Example 1 
torch.zeros(5)

tensor([0., 0., 0., 0., 0.])

Example 1 creates a 1 dimensional tensor with shape 5 whose values are set to zero 

In [ ]:
# Example 2 
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

Example 2 creates a tensor with shape (2,3) whose values are set to zero 

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
torch.zeros(5.5)

TypeError: ignored

shape should be integer

We use this function when we want to create a zero tensor with shape as argument 

Let's save our work using Jovian before continuing.

In [ ]:
!pip install jovian --upgrade --quiet

     |████████████████████████████████| 68 kB 4.0 MB/s 


In [ ]:
import jovian

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ··········
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/ashutosh-dinesh/01-tensor-operations


'https://jovian.ai/ashutosh-dinesh/01-tensor-operations'

## Function 2 - TORCH.ARANGE
torch.arange(start=0, end, step=1, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)

start (Number) – the starting value for the set of points. Default: 0.

end (Number) – the ending value for the set of points

step (Number) – the gap between each pair of adjacent points. Default: 1.


In [ ]:
# Example 1 
torch.arange(5)

tensor([0, 1, 2, 3, 4])

Returns a 1-D tensor of size 5  with step 1

In [ ]:
# Example 2 - working
torch.arange(1, 4)

tensor([1, 2, 3])

Returns a 1-D tensor of size 3  with starting with 1 and ending before 4 with step 1

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
torch.arange(1, 0.5, 2.5)

RuntimeError: ignored

End value should always be greater than step size 

Use this function when you want to create a tensor with sqeuential values

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/ashutosh-dinesh/01-tensor-operations


'https://jovian.ai/ashutosh-dinesh/01-tensor-operations'


## Function 3 - torch.linspace

Creates a one-dimensional tensor of size steps whose values are evenly spaced from start to end, inclusive

torch.linspace(start, end, steps, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor

start (float) – the starting value for the set of points

end (float) – the ending value for the set of points

steps (int) – size of the constructed tensor

In [ ]:
# Example 1 - working
torch.linspace(3, 10, steps=5)

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

Example 1 creates a 1-Dimensional tensor of size 5 with starting value as 3 and end value as 10 

In [ ]:
# Example 2 - working
torch.linspace(-10, 10, steps=5)

tensor([-10.,  -5.,   0.,   5.,  10.])

Example 1 creates a 1-Dimensional tensor of size 5 with starting value as -10 and end value as 10 

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
torch.linspace(start=10, end=0)

TypeError: ignored

Step should always have a value

Use this function when you want to create a fixed size tensor with evenly spaced having values from start to end 

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/ashutosh-dinesh/01-tensor-operations


'https://jovian.ai/ashutosh-dinesh/01-tensor-operations'

## Function 4 - torch.narrow

Returns a new tensor that is a narrowed version of input tensor. The dimension dim is input from start to start + length. The returned tensor and input tensor share the same underlying storage.

torch.narrow(input, dim, start, length) → Tensor

In [ ]:
# Example 1 - working
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
torch.narrow(x, 0, 0, 2)

tensor([[1, 2, 3],
        [4, 5, 6]])

new tensor is the narrowed tensor along dimension 0 starting from index to index 2 inclusive

In [ ]:
# Example 2 - working
torch.narrow(x, 1, 1, 2)


tensor([[2, 3],
        [5, 6],
        [8, 9]])

new tensor is the narrowed tensor along dimension 1 starting from index to index 2 inclusive

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
torch.narrow(x, 1, 1, 3)

RuntimeError: ignored

start (1) + length (3) should not exceed dimension size (3).

Use this function to narrow an existing tensor 

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/ashutosh-dinesh/01-tensor-operations


'https://jovian.ai/ashutosh-dinesh/01-tensor-operations'

## Function 5 - torch.transpose

Returns a tensor that is a transposed version of input. The given dimensions dim0 and dim1 are swapped.

If input is a strided tensor then the resulting out tensor shares its underlying storage with the input tensor, so changing the content of one would change the content of the other.

If input is a sparse tensor then the resulting out tensor does not share the underlying storage with the input tensor.\

torch.transpose(input, dim0, dim1) → Tensor

In [ ]:
x = torch.tensor([[[1, 2], [4, 5], [7, 8]]])
torch.transpose(x, 0, 1)

tensor([[[1, 2]],

        [[4, 5]],

        [[7, 8]]])

Returns the transposed version of the input tensor in dimension 0

In [ ]:
torch.transpose(x, 0, 2)

tensor([[[1],
         [4],
         [7]],

        [[2],
         [5],
         [8]]])

Returns the transposed version of the input tensor in dimension 1

In [ ]:
torch.transpose(x, 3, 1)

IndexError: ignored

Dimension should have value between -n to n-1

Use the function to get the transpose of a multidimensional tensor 

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/ashutosh-dinesh/01-tensor-operations


'https://jovian.ai/ashutosh-dinesh/01-tensor-operations'

## Conclusion


5 tensor operations were covered in this notebook 

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* ...

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/ashutosh-dinesh/01-tensor-operations


'https://jovian.ai/ashutosh-dinesh/01-tensor-operations'